### Taller 2b - Matriz Inversa y Descomposición LU

Nombre: Carolay Pillajo

Curso: GR1CC

Haga modificaciones a las funciones base del siguiente código:
https://github.com/ztjona/MN-prueba-02/tree/main

1. para encontrar la matriz inversa de las siguientes matrices:

A1 =
\begin{bmatrix}
1 & 3 & 4 \\
2 & 1 & 3 \\
4 & 2 & 1
\end{bmatrix}


In [26]:
# ####################################################################
def gauss_jordan(A: np.ndarray) -> np.ndarray:
    """Resuelve un sistema de ecuaciones lineales mediante el método de eliminación gaussiana.

    ## Parameters

    `A`: matriz aumentada del sistema de ecuaciones lineales. Debe ser de tamaño n-by-(n+1), donde n es el número de incógnitas.

    ## Return

    `solucion`: vector con la solución del sistema de ecuaciones lineales.

    """
    if not isinstance(A, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        A = np.array(A, dtype = float)
    n = A.shape[0]

    for i in range(0, n):  # loop por columna

        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if A[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(A[pi, i]) < abs(A[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            raise ValueError("No existe solución única.")

        if p != i:
            # swap rows
            logging.debug(f"Intercambiando filas {i} y {p}")
            _aux = A[i, :].copy()
            A[i, :] = A[p, :].copy()
            A[p, :] = _aux

        # --- Eliminación: loop por fila
        #for j in range(i + 1, n): Eliminacion Gaussiana
        for j in range(0, n):
            if j == i:
                continue
            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]

        logging.info(f"\n{A}")

    if A[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

        print(f"\n{A}")
    """""
    # --- Sustitución hacia atrás   
    solucion = np.zeros(n)
    solucion[n - 1] = A[n - 1, n] / A[n - 1, n - 1]

    for i in range(n - 2, -1, -1):
        suma = 0
        for j in range(i + 1, n):
            suma += A[i, j] * solucion[j]
        solucion[i] = (A[i, n] - suma) / A[i, i]
    """
    return A

NameError: name 'np' is not defined

In [ ]:
A1 = [[1, 3, 4], [2, 1, 3], [4, 2, 1]]
n = len(A1)
Ag=np.hstack((A1,np.eye(n)))
gauss_jordan(Ag)

[01-13 17:17:13][INFO] 
[[  1.   3.   4.   1.   0.   0.]
 [  0.  -5.  -5.  -2.   1.   0.]
 [  0. -10. -15.  -4.   0.   1.]]
[01-13 17:17:13][INFO] 
[[ 1.   0.   1.  -0.2  0.6  0. ]
 [ 0.  -5.  -5.  -2.   1.   0. ]
 [ 0.   0.  -5.   0.  -2.   1. ]]
[01-13 17:17:13][INFO] 
[[ 1.   0.   0.  -0.2  0.2  0.2]
 [ 0.  -5.   0.  -2.   3.  -1. ]
 [ 0.   0.  -5.   0.  -2.   1. ]]


array([[ 1. ,  0. ,  0. , -0.2,  0.2,  0.2],
       [ 0. , -5. ,  0. , -2. ,  3. , -1. ],
       [ 0. ,  0. , -5. ,  0. , -2. ,  1. ]])

A2 =
\begin{bmatrix}
1 & 2 & 3 \\
0 & 1 & 4 \\
5 & 6 & 0
\end{bmatrix}

In [ ]:
A2 = [[1, 2, 3], [0, 1, 4], [5, 6, 0]]
n = len(A2)
Ag=np.hstack((A2,np.eye(n)))
gauss_jordan(Ag)

[01-13 17:17:16][INFO] 
[[  1.   2.   3.   1.   0.   0.]
 [  0.   1.   4.   0.   1.   0.]
 [  0.  -4. -15.  -5.   0.   1.]]
[01-13 17:17:16][INFO] 
[[ 1.  0. -5.  1. -2.  0.]
 [ 0.  1.  4.  0.  1.  0.]
 [ 0.  0.  1. -5.  4.  1.]]
[01-13 17:17:16][INFO] 
[[  1.   0.   0. -24.  18.   5.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]


array([[  1.,   0.,   0., -24.,  18.,   5.],
       [  0.,   1.,   0.,  20., -15.,  -4.],
       [  0.,   0.,   1.,  -5.,   4.,   1.]])

A3 =
\begin{bmatrix}
4 & 2 & 1 \\
2 & 1 & 3 \\
1 & 3 & 4
\end{bmatrix}

In [ ]:
A3 = [[4, 2, 1], [2, 1, 3], [1, 3, 4]]
n = len(A3)
Ag=np.hstack((A3,np.eye(n)))
gauss_jordan(Ag)

[01-13 17:17:58][INFO] 
[[  1.   3.   4.   0.   0.   1.]
 [  0.  -5.  -5.   0.   1.  -2.]
 [  0. -10. -15.   1.   0.  -4.]]
[01-13 17:17:58][INFO] 
[[ 1.   0.   1.   0.   0.6 -0.2]
 [ 0.  -5.  -5.   0.   1.  -2. ]
 [ 0.   0.  -5.   1.  -2.   0. ]]
[01-13 17:17:58][INFO] 
[[ 1.   0.   0.   0.2  0.2 -0.2]
 [ 0.  -5.   0.  -1.   3.  -2. ]
 [ 0.   0.  -5.   1.  -2.   0. ]]


array([[ 1. ,  0. ,  0. ,  0.2,  0.2, -0.2],
       [ 0. , -5. ,  0. , -1. ,  3. , -2. ],
       [ 0. ,  0. , -5. ,  1. , -2. ,  0. ]])

A4 =
\begin{bmatrix}
2 & 4 & 6 & 1 \\
4 & 7 & 5 & -6 \\
2 & 5 & 18 & 10 \\
6 & 12 & 38 & 16
\end{bmatrix}

In [ ]:
A4 = [[2,4,6,1], [4,7,5,-6], [2,5,18,10], [6,12,38,16]]
n = len(A4)
Ag=np.hstack((A4,np.eye(n)))
gauss_jordan(Ag)

[01-13 17:19:17][INFO] 
[[ 2.  4.  6.  1.  1.  0.  0.  0.]
 [ 0. -1. -7. -8. -2.  1.  0.  0.]
 [ 0.  1. 12.  9. -1.  0.  1.  0.]
 [ 0.  0. 20. 13. -3.  0.  0.  1.]]
[01-13 17:19:17][INFO] 
[[  2.   0. -22. -31.  -7.   4.   0.   0.]
 [  0.  -1.  -7.  -8.  -2.   1.   0.   0.]
 [  0.   0.   5.   1.  -3.   1.   1.   0.]
 [  0.   0.  20.  13.  -3.   0.   0.   1.]]
[01-13 17:19:17][INFO] 
[[  2.    0.    0.  -26.6 -20.2   8.4   4.4   0. ]
 [  0.   -1.    0.   -6.6  -6.2   2.4   1.4   0. ]
 [  0.    0.    5.    1.   -3.    1.    1.    0. ]
 [  0.    0.    0.    9.    9.   -4.   -4.    1. ]]
[01-13 17:19:17][INFO] 
[[ 2.          0.          0.          0.          6.4        -3.42222222
  -7.42222222  2.95555556]
 [ 0.         -1.          0.          0.          0.4        -0.53333333
  -1.53333333  0.73333333]
 [ 0.          0.          5.          0.         -4.          1.44444444
   1.44444444 -0.11111111]
 [ 0.          0.          0.          9.          9.         -4.
  -4.          1

array([[ 2.        ,  0.        ,  0.        ,  0.        ,  6.4       ,
        -3.42222222, -7.42222222,  2.95555556],
       [ 0.        , -1.        ,  0.        ,  0.        ,  0.4       ,
        -0.53333333, -1.53333333,  0.73333333],
       [ 0.        ,  0.        ,  5.        ,  0.        , -4.        ,
         1.44444444,  1.44444444, -0.11111111],
       [ 0.        ,  0.        ,  0.        ,  9.        ,  9.        ,
        -4.        , -4.        ,  1.        ]])

2. Calcule la descomposición LU para estas matrices y encuentre la solución para estos vectores de valores independientes b.

b1 =
\begin{bmatrix}
1 \\
2 \\
4
\end{bmatrix}

In [ ]:
from src import descomposicion_LU,resolver_LU

[01-13 17:41:54][INFO] 2026-01-13 17:41:54.398784
[01-13 17:41:54][INFO] 2026-01-13 17:41:54.553642


In [ ]:
A1 = [[1, 3, 4], [2, 1, 3], [4, 2, 1]]

L,U = descomposicion_LU(A1)

print(L)

[01-13 17:44:45][INFO] 
[[  1.   3.   4.]
 [  0.  -5.  -5.]
 [  0. -10. -15.]]
[01-13 17:44:45][INFO] 
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
[01-13 17:44:45][INFO] 
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
[[1. 0. 0.]
 [2. 1. 0.]
 [4. 2. 1.]]


In [ ]:
b1 = [1, 2, 4]

resolver_LU(L, U, b1)

[01-13 17:45:59][INFO] Sustitución hacia adelante
[01-13 17:45:59][INFO] y = 
[[1.]
 [0.]
 [0.]]
[01-13 17:45:59][INFO] Sustitución hacia atrás
[01-13 17:45:59][INFO] i = 1
[01-13 17:45:59][INFO] suma = [0.]
[01-13 17:45:59][INFO] U[i, i] = -5.0
[01-13 17:45:59][INFO] y[i] = [0.]
[01-13 17:45:59][INFO] i = 0
[01-13 17:45:59][INFO] suma = [0.]
[01-13 17:45:59][INFO] U[i, i] = 1.0
[01-13 17:45:59][INFO] y[i] = [1.]


array([[ 1.],
       [-0.],
       [-0.]])

b2 =
\begin{bmatrix}
3 \\
-5 \\
2
\end{bmatrix}

In [ ]:
A2 = [[1, 2, 3], [0, 1, 4], [5, 6, 0]]

L,U = descomposicion_LU(A2)

print(L)

[01-13 17:47:12][INFO] 
[[  1.   2.   3.]
 [  0.   1.   4.]
 [  0.  -4. -15.]]
[01-13 17:47:12][INFO] 
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
[01-13 17:47:12][INFO] 
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 5. -4.  1.]]


In [ ]:
b2 = [3, -5, 2]

resolver_LU(L, U, b2)

[01-13 17:47:52][INFO] Sustitución hacia adelante
[01-13 17:47:52][INFO] y = 
[[  3.]
 [ -5.]
 [-33.]]
[01-13 17:47:52][INFO] Sustitución hacia atrás
[01-13 17:47:52][INFO] i = 1
[01-13 17:47:52][INFO] suma = [-132.]
[01-13 17:47:52][INFO] U[i, i] = 1.0
[01-13 17:47:52][INFO] y[i] = [-5.]
[01-13 17:47:52][INFO] i = 0
[01-13 17:47:52][INFO] suma = [155.]
[01-13 17:47:52][INFO] U[i, i] = 1.0
[01-13 17:47:52][INFO] y[i] = [3.]


array([[-152.],
       [ 127.],
       [ -33.]])

b3 =
\begin{bmatrix}
7 \\
8 \\
-1
\end{bmatrix}

In [ ]:
A3 = [[4, 2, 1], [2, 1, 3], [1, 3, 4]]

L,U = descomposicion_LU(A3)

print(L)

[01-13 17:50:04][INFO] 
[[4.   2.   1.  ]
 [0.   0.   2.5 ]
 [0.   2.5  3.75]]


ValueError: No existe solución única.

In [ ]:
b3 = [7, 8, -1]

resolver_LU(L, U, b3)

[01-13 17:49:47][INFO] Sustitución hacia adelante
[01-13 17:49:47][INFO] y = 
[[ 7.]
 [ 8.]
 [-4.]]
[01-13 17:49:47][INFO] Sustitución hacia atrás
[01-13 17:49:47][INFO] i = 1
[01-13 17:49:47][INFO] suma = [-16.]
[01-13 17:49:47][INFO] U[i, i] = 1.0
[01-13 17:49:47][INFO] y[i] = [8.]
[01-13 17:49:47][INFO] i = 0
[01-13 17:49:47][INFO] suma = [36.]
[01-13 17:49:47][INFO] U[i, i] = 1.0
[01-13 17:49:47][INFO] y[i] = [7.]


array([[-29.],
       [ 24.],
       [ -4.]])

b1 =
\begin{bmatrix}
1 \\
2 \\
4 \\
5
\end{bmatrix}

In [ ]:
A4 = [[2,4,6,1], [4,7,5,-6], [2,5,18,10], [6,12,38,16]]

L,U = descomposicion_LU(A4)

print(L)

[01-13 17:51:58][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  1. 12.  9.]
 [ 0.  0. 20. 13.]]
[01-13 17:51:58][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0. 20. 13.]]
[01-13 17:51:58][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 17:51:58][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 1. -1.  1.  0.]
 [ 3. -0.  4.  1.]]


In [ ]:
b1 = [1, 2, 4, 5]

resolver_LU(L, U, b1)

[01-13 17:52:47][INFO] Sustitución hacia adelante
[01-13 17:52:47][INFO] y = 
[[  1.]
 [  0.]
 [  3.]
 [-10.]]
[01-13 17:52:47][INFO] Sustitución hacia atrás
[01-13 17:52:47][INFO] i = 2
[01-13 17:52:47][INFO] suma = [-1.11111111]
[01-13 17:52:47][INFO] U[i, i] = 5.0
[01-13 17:52:47][INFO] y[i] = [3.]
[01-13 17:52:47][INFO] i = 1
[01-13 17:52:47][INFO] suma = [3.13333333]
[01-13 17:52:47][INFO] U[i, i] = -1.0
[01-13 17:52:47][INFO] y[i] = [0.]
[01-13 17:52:47][INFO] i = 0
[01-13 17:52:47][INFO] suma = [16.35555556]
[01-13 17:52:47][INFO] U[i, i] = 2.0
[01-13 17:52:47][INFO] y[i] = [1.]


array([[-7.67777778],
       [ 3.13333333],
       [ 0.82222222],
       [-1.11111111]])

b2 =
\begin{bmatrix}
3 \\
-5 \\
2 \\
6
\end{bmatrix}

In [ ]:
A4 = [[2,4,6,1], [4,7,5,-6], [2,5,18,10], [6,12,38,16]]

L,U = descomposicion_LU(A4)

print(L)

[01-13 17:52:05][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  1. 12.  9.]
 [ 0.  0. 20. 13.]]
[01-13 17:52:05][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0. 20. 13.]]
[01-13 17:52:05][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 17:52:05][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 1. -1.  1.  0.]
 [ 3. -0.  4.  1.]]


In [ ]:
b2 = [3, -5, 2, 6]

resolver_LU(L, U, b2)

[01-13 17:53:29][INFO] Sustitución hacia adelante
[01-13 17:53:29][INFO] y = 
[[  3.]
 [-11.]
 [-12.]
 [ 45.]]
[01-13 17:53:29][INFO] Sustitución hacia atrás
[01-13 17:53:29][INFO] i = 2
[01-13 17:53:29][INFO] suma = [5.]
[01-13 17:53:29][INFO] U[i, i] = 5.0
[01-13 17:53:29][INFO] y[i] = [-12.]
[01-13 17:53:29][INFO] i = 1
[01-13 17:53:29][INFO] suma = [-16.2]
[01-13 17:53:29][INFO] U[i, i] = -1.0
[01-13 17:53:29][INFO] y[i] = [-11.]
[01-13 17:53:29][INFO] i = 0
[01-13 17:53:29][INFO] suma = [-36.2]
[01-13 17:53:29][INFO] U[i, i] = 2.0
[01-13 17:53:29][INFO] y[i] = [3.]


array([[19.6],
       [-5.2],
       [-3.4],
       [ 5. ]])

b3 =
\begin{bmatrix}
7 \\
8 \\
-1 \\
0
\end{bmatrix}

In [ ]:
A4 = [[2,4,6,1], [4,7,5,-6], [2,5,18,10], [6,12,38,16]]

L,U = descomposicion_LU(A4)

print(L)

[01-13 17:52:12][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  1. 12.  9.]
 [ 0.  0. 20. 13.]]
[01-13 17:52:12][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0. 20. 13.]]
[01-13 17:52:12][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 17:52:12][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 1. -1.  1.  0.]
 [ 3. -0.  4.  1.]]


In [ ]:
b3 = [7, 8, -1, 0]

resolver_LU(L, U, b3)

[01-13 17:53:51][INFO] Sustitución hacia adelante
[01-13 17:53:51][INFO] y = 
[[  7.]
 [ -6.]
 [-14.]
 [ 35.]]
[01-13 17:53:51][INFO] Sustitución hacia atrás
[01-13 17:53:51][INFO] i = 2
[01-13 17:53:51][INFO] suma = [3.88888889]
[01-13 17:53:51][INFO] U[i, i] = 5.0
[01-13 17:53:51][INFO] y[i] = [-14.]
[01-13 17:53:51][INFO] i = 1
[01-13 17:53:51][INFO] suma = [-6.06666667]
[01-13 17:53:51][INFO] U[i, i] = -1.0
[01-13 17:53:51][INFO] y[i] = [-6.]
[01-13 17:53:51][INFO] i = 0
[01-13 17:53:51][INFO] suma = [-17.84444444]
[01-13 17:53:51][INFO] U[i, i] = 2.0
[01-13 17:53:51][INFO] y[i] = [7.]


array([[12.42222222],
       [-0.06666667],
       [-3.57777778],
       [ 3.88888889]])